# Generated by Django 5.2.1 on 2025-05-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
    ]
